### ISSUE TITLE
Maven Repo Out of Date

### ISSUE THREAD

**Issue by DraftiestHat** [gisgraphy/gisgraphy-utils#2]
I was looking at your Maven repository (http://gisgraphy.free.fr/mavenrepo) and the newest version of gisgraphy-utils is 1.0, whereas this is on 5.0-beta2. Is it possible to have you guys update your repository?

**Comment by gisgraphy** [comment]
you are right. I have updated the repository for all Gisgraphy-* libraries

**Comment by DraftiestHat** [comment]
That was incredibly fast!! Thank you! You all are wonderful.
